language: ruby
rvm: 2.1.5
script: bin/rake spec
before_install:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
deploy:
  provider: heroku
  api_key:
    secure: i3SsEOMKkqeSvX5sBD5xF4oqveiWDKy5CDQasE2nEnJGuJKyGP/WNbsrr1Cqr1UTM7qap3Cg+E6T4E8NKvOkyJ5RlYJOFwbIwCoZx7Ofcu0ChAHNPgmuvLzwDeLlXJ8tmQKINdbJMJaCizDNRwWpSnQ9ULY7/YgVXYIVW4KRd+c=
  app: enigmatic-springs-5916
  on:
    repo: runarf/ticketee
